# Generated by Django 5.2.17 on 2026-09-13 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA/SMK'), ('kuliah', 'Kuliah')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
